name: BootcampClase2Steps

on: [push]

jobs:

    primer_job:
        runs-on: ubuntu-latest

        steps:
            - name: Primer paso (Saludo)
              run: echo "Hola, mundo"

    segundo_job:
        runs-on: windows-latest
        
        needs: primer_job

        steps:
            - name: Ejecutando después el primer job
              run: echo "Ejecutando después el primer job"
    



